### ISSUE TITLE
Source Map generation is very slow with gulp-souremaps

### ISSUE THREAD

**Issue by jongunter** [stevelacy/gulp-less#248]
I'm generating JavaScript source maps and things are running pretty fast (under one second). However, as soon as I set up source maps on my task that runs `gulp-less`, the execution time jumps from 1 second to 20 seconds.

More details are here: https://github.com/floridoo/gulp-sourcemaps/issues/215
I'm not sure if this is an issue with `gulp-less` or `gulp-sourcemaps`.

**Comment by contra** [comment]
Can you use gulp-debug before and after less to see if less is taking 20 seconds?
