### ISSUE TITLE
silent option?

### ISSUE THREAD

**Issue by stevenvachon** [stevelacy/gulp-less#251]
http://lesscss.org/usage/index.html#command-line-usage-silent

It'd be great if we could use this option programmatically to silence gulp-less debug logs. This becomes important when building the same files multiple times with different options, and only needing to see a set of errors once.

**Comment by stevelacy** [comment]
Passing `silent: true` into the less options is passed into the less compiler

**Comment by stevenvachon** [comment]
Errors are still being logged. Use v3.3.2

**Comment by stevenvachon** [comment]
Sorry, error is coming from elsewhere.
