### ISSUE TITLE
New version seems to ignore .css imports

### ISSUE THREAD

**Issue by danielverejan** [stevelacy/gulp-less#267]
Updated to the 3.3.0 and it doesn't work with .css imports.
In my projects in throws an error saying 

> Ignoring local @import of "lib/foundation.css" as resource is missing.

Made a separate project to test it and have no errors but it still doesn't import .css file.
Gulpfile:
```javascript
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('less', function() {
	return gulp.src('./src/index.less')
	.pipe(less())
	.pipe(gulp.dest('build'));
});
```
index.less
```css
@import 'file.css';

body {
	background: green;
}
```

result:
`@import 'file.css';
body {
  background: green;
}
`

Using latest gulp and gulp-less on windows 10.

**Comment by joelharkes** [comment]
Seem to have the same issue here. any reason why this could be happening?

**Comment by danielverejan** [comment]
Don't know what is the reason but this solved my issue.
`@import (less) 'lib/foundation.css';`  
add **(less)** before the url or **(inline)** to load it raw

**Comment by amazingrando** [comment]
@danielverejan Adding `(less)` solved my problem. Thank you.

**Comment by butuzov** [comment]
This is not a gulp-less issue, but a gulp-clean-css. 
Downgrade to 2.3.2 version to have css imports working again (if you using multiple font-face statements)

**Comment by stevelacy** [comment]
Closing as it seems it is a vendor issue (less.js)
