### ISSUE TITLE
Support Less 3.X

### ISSUE THREAD

**Issue by lvl99** [stevelacy/gulp-less#269]
New Less! I wanna use it.

**Comment by stevelacy** [comment]
It has not been released yet.

**Comment by wik-z** [comment]
It has now. Still can't use gulp-less with less v.3

**Comment by stevelacy** [comment]
> wik-z commented an hour ago
  It has now. Still can't use gulp-less with less v.3







@wik-z I am extremely annoyed by your entitled attitude. Either contribute to OSS software or don't complain when others write code and give it for free.
As of right now less@3.0.0 was released **17 hours ago**. Today is a weekend. Get it together.

Want to contribute? Well then send a PR to `accord` to add support for less@3.0.0. Here is the example file for less@2.0.0 https://github.com/jescalan/accord/blob/master/lib/adapters/less/2.x.coffee

**Comment by wik-z** [comment]
Whoa man, take it easy. Apologies for that, I can assure you that's not what I meant.
I use different build tools for different projects, gulp is one of them but haven't used it in a while. I had to set up a project with gulp-less yesterday. I normally don't really focus on the versions of everything, I just use the latest on new projects, and that's how I noticed that gulp-less isn't supporting less v3 yet. Googled it, found this issue, looked at the date of the first post here and decided to leave a comment to drag authors attention to it. I literally had no idea it's just been released.

I appreciate the work you do and would love to contribute, gulp-less is an awesome tool. I'll try to have a look on that v3 soon.

**Comment by stevelacy** [comment]
Awesome, no worries!
I've a long schedule this week, but will try to get around to this.

**Comment by stevelacy** [comment]
https://github.com/jescalan/accord/issues/336

**Comment by lipis** [comment]
Yes please!
