### ISSUE TITLE
Inject Variables

### ISSUE THREAD

**Issue by crazyjat** [stevelacy/gulp-less#273]
I need a way to inject/override a variable for production builds. 

For example, I use bootstrap in my project and for development the Glyphicons Halflings font is served from node_modules/bootstrap/fonts directory. However, I have a gulp task to collect the fonts and output them into my dist folder at the root of the site /fonts.

It would be quite handy to be able to inject/override a less variable from this gulp plugin.

Thanks

**Comment by stevelacy** [comment]
Already supported. Pass `modifyVars` or `globalVars` as the options argument.

**Comment by crazyjat** [comment]
tried that. modifyVars is broken currently. Doesn't actually inject the variable before compiling less to css. It is adding the variable to the end of the file after compiling to css.
