### ISSUE TITLE
Add an option to ignore bad files

### ISSUE THREAD

**Issue by jdnichollsc** [stevelacy/gulp-less#274]
Hi guys,

Thanks for this excellent plugin, can you add an option to ignore bad files? 
Check my issue please:
```
[01:12:24] Starting 'less'...
Potentially unhandled rejection [2] variable @icon-font-path is undefined in file C:\dev\bevyup\dashboard_client\src\BevyUp.DashboardClient.Web\wwwroot\App\css\glyphicons.less line no. 13
```

I want to execute the next pipe **(gulp.dest)** ignoring the bad files.
My package.json:
```json
{
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-uglify": "^3.0.0",
    "run-sequence": "^1.2.2",
    "gulp-less": "^3.3.2",
    "gulp-plumber": "^1.1.0",
    "gulp-rev": "^7.1.2"
  }
}
```

Thanks in advance, Nicholls

**Comment by stevelacy** [comment]
Bad files? 
This is a plugin that takes the input source from `gulp.src`. Use the proper glob matching to ignore the "bad files" from gulp.

https://stackoverflow.com/a/24648667/1041104

**Comment by jdnichollsc** [comment]
Hi @stevelacy,
Thanks for your quickly response, I want to ignore file exceptions, Is it possible?
Thanks
