### ISSUE TITLE
why i use gulp-less transform z-index, the less output a strange value

### ISSUE THREAD

**Issue by hunghoo** [stevelacy/gulp-less#275]
for example: 
```
less:
z-index:  1000;
```
i got this:

```
css:
z-index: 7;
```

**Comment by stevelacy** [comment]
not related to this project - open on less.js

**Comment by hunghoo** [comment]
i found this error that cause the error baeause  i didt add this config "paths: [ path.join(__dirname, 'less', 'includes') ]"

**Comment by hunghoo** [comment]
i found why cause this error,  because i didt add this config "paths: [ path.join(__dirname, 'less', 'includes') ]"
