### ISSUE TITLE
gulp-notify: [Error running Gulp] File: .. is undefined in file .less

### ISSUE THREAD

**Issue by Alecto** [stevelacy/gulp-less#278]
i did task
```
gulp.task('less', function () {
  return gulp.src('less/**/*.less')
    .pipe(sourcemaps.init())
    .pipe(less().on("error", notify.onError(function (error) {
        return "File: " + error.message;
      })))
    .pipe(gcmq())
    .pipe(autoprefixer({
            browsers: ['last 5 versions', '> 1%'],
            cascade: true
        }))
    .pipe(notify({
      message: 'Compiled!',
      sound: false
    }))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('.css'))
    .pipe(browserSync.reload({stream: true}));
});
```

and compile style.less
```
@import "_smart-grid";
@import "_common";
```
compilation is performed, but I'm constantly getting an error:
`[21:43:21] gulp-notify: [Error running Gulp] File: .row-flex is undefined in file D:\webProjects\test\test-sass\less\_common.less line no. 8
`
The same code for sass and scss works without any error.

**Comment by stevelacy** [comment]
That is a syntax error or space/tab indentation error in your less code, nothing related to this plugin

**Comment by Alecto** [comment]
_common.less line no. 8:
```
.row {
  .row-flex();
}
```
_smart-grid.less
```
.row-flex(){
    display: flex;
    flex-wrap: wrap;
    margin-left: (@offset_one_side * -1);
    margin-right: (@offset_one_side * -1);
}
```

I see no errors in the code

**Comment by stevelacy** [comment]
Can you create an example repo to reproduce the issue? I'll close until then

**Comment by seven-phases-max** [comment]
>`gulp.src('less/**/*.less')`

This compiles *all* files in your "less" directories. Thus `_common.less` is also compiled separately and there's no `.row-flex` defined there (`_common.less` itself does not import `_smart-grid.less`).

You need to change that `glp.src` to compile `style.less` *only* (or filter "leading_underscore" files for `/*.less` if there other files to compile beside).

**Comment by Alecto** [comment]
I'll try your advice, thanks.
