### ISSUE TITLE
Support the "strictMath" option

### ISSUE THREAD

**Issue by dsine-de** [stevelacy/gulp-less#279]
Add support for the strict math option (http://lesscss.org/usage/#command-line-usage-strict-math), e.g.:

```js
...
.pipe(less({strictMath: 'on'})
...
```

Sometimes the automatic internal calculation of LESS come in your way.

**Comment by stevelacy** [comment]
All options are passed directly to less, this plugin does not give extra support for more options.
https://github.com/stevelacy/gulp-less/blob/master/index.js#L37

**Comment by dsine-de** [comment]
Ah, thanks! I'll try to find out why this option is not working then.
