### ISSUE TITLE
gulp-less not update @import files in main less

### ISSUE THREAD

**Issue by Tixxxon** [stevelacy/gulp-less#284]
gulp.task('less:style', function () {
  return gulp.src(['./src/less/style.less'])
    .pipe(less({
      paths: ['./src/less/includes']
    }))
    .pipe(gulp.dest('./built/css/'));
});
gulp.task('watch', function () {
  gulp.watch(['./src/less/**/*.less'], ['less:style']);
});

### style.less
@import 'button.less'

while I start gulp watch, all work fine, but if I change button.less, less:style activated, but style.css not updated.  What am I doing wrong?

gulp 3.9.1
gulp-less 4.0.0

**Comment by stevelacy** [comment]
Duplicate, search issues please #283
