### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by JukkaM** [stevelacy/gulp-less#287]
I'm not sure whether this is a problem in gulp-less or accord but because the error occurs when using gulp-less I posted the issue first here. 

I have two very similar projects which have almost identical package.json files. They both have gulp-less as a devDependency and they both have identical gulpfile.js. When running my gulp task for less in project A, everything goes smoothly. But in project B, I get an error:

module.js:549
    throw err;
    ^

Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at resolve_engine_path (C:\projectpath\node_modules\accord\lib\index.js:67:18)
    at Object.exports.load (C:\projectpath\node_modules\accord\lib\index.js:25:19)
    at Object.<anonymous> (C:\projectpath\node_modules\gulp-less\index.js:9:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

The only difference I have found so far is that in project A accord and less are installed under gulp-less:

+-- gulp-less@4.0.0
| +-- accord@0.29.0
| +-- less@3.0.2

In project B, where the problem occurs, accord is installed directly in my node_modules directory and less is located under the gulp-less node_modules path:

+-- accord@0.29.0
+-- gulp-less@4.0.0
| +-- less@3.0.2

So, I guess that the differencies between package.json files in project A and B makes this difference in module installation tree but I think that this error shouldn't occur in either set up. If I manually copy-paste the accord directory in project B from the project's root node_modules directory under the gulp-less' node_modules directory and run my less task, everything works fine.

I have removed my node_modules directories in both projects and installed packages again. The problem still remains. I have also cleared my npm cache but that didn't help either.

However, I can "resolve" the problem if I delete package-lock.json and install packages again. After that, npm installs accord and less directly under the project's node_modules directory. But I don't want to delete my package-lock.json file.

As I said, my opinion is that gulp-less should work in the scenario where accord and less are in different levels in dependency tree.

**Comment by stevelacy** [comment]
This is a problem with npm/node and the package-lock. 
I can not change this project or accord to fix the problem with npm. 
My only suggestion is to manually check the package-lock and update it, assuming a later version of npm fixed it.
