### ISSUE TITLE
Release v3.5.0 listed as current on npm even though v4.0.0 has been published

### ISSUE THREAD

**Issue by dpilafian** [stevelacy/gulp-less#289]
https://www.npmjs.com/package/gulp-less
![npm-gulp-less-v4 0 0](https://user-images.githubusercontent.com/119555/39608644-bf74f208-4ef7-11e8-9431-b0fefc9e1635.png)
![npm-update](https://user-images.githubusercontent.com/119555/39608699-2eccf11e-4ef8-11e8-89c5-c0aa09ca44dc.png)

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-less/issues/283#issuecomment-386069118
