### ISSUE TITLE
Error: less version not supported

### ISSUE THREAD

**Issue by mistergoodson** [stevelacy/gulp-less#291]
Getting `Error: less version 3.0.1 is not currently supported` when running `require('gulp-less');`, but github page says Less `>= 2.x` should be supported.

Tried updating Less to `3.0.4` (latest) but getting same error.

Am I doing something wrong or is Less 3.x just not supported yet?

**Comment by stevelacy** [comment]
Yes, less@3 has many issues in their core relating to caching files. Currently tracking it here:
https://github.com/stevelacy/gulp-less/issues/283
